### ISSUE TITLE
Cannot install Extras for Eclipse

### ISSUE THREAD

**Issue by konfri** [rherrmann/eclipse-extras#59]
Hey :)

I'm trying to install you plugins with a fresh Neon.3 instance, that I just download from:

http://www.eclipse.org/downloads/packages/eclipse-ide-java-developers/neon3

![eclipse_extras_01](https://cloud.githubusercontent.com/assets/16843990/25577690/875a9d92-2e68-11e7-936a-4b7c5d5709b2.png)
![eclipse_extras_02](https://cloud.githubusercontent.com/assets/16843990/25577691/875ab944-2e68-11e7-8690-2c86b7caaa76.png)

Can you help out? :)

**Comment by rherrmann** [comment]
Thanks for pointing out this issue. The problem should be fixed with commit 762f718ee4545aed955d9da0b7bafb6e0183eb72. Please re-open if there are further issues.

Make sure to restart Eclipse before retrying to install Extras for Eclipse. Otherwise, the p2 installer might use cached contents and show the same error again.

**Comment by konfri** [comment]
Thank you for the fix :)
