### ISSUE TITLE
Integration of TestNG in JUnitStatus

### ISSUE THREAD

**Issue by makkimesser** [rherrmann/eclipse-extras#64]
Maybe the Plugin could be extended to show tests running with TestNG as well?

I'm willing to provide a pullrequest if usefull if requested.

**Comment by rherrmann** [comment]
Eclipse provides a generic [TestRunListener](https://help.eclipse.org/2020-06/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fjunit%2FTestRunListener.html) that plug-ins can use to get notifications about running tests. Despite its name, the _JUnit status bar_ uses this infrastructure to show progress.

If the [TestNG Eclipse plug-in](https://testng.org/doc/eclipse.html) supports this infrastructure, the status bar should just work. The UI may need to use a more general name

Otherwise, it seems a better fit to contribute a status bar to the TestNG Eclipse repository (https://github.com/cbeust/testng-eclipse). What do you think?

**Comment by makkimesser** [comment]
So far TestNG-Eclipse supports the ILaunchListener, that's not the problem.

But we have to come from ```ILaunchListener``` to ```ITestRunSession```, that is restricted API

```
Restriction:
This interface is not intended to be implemented by clients.
Restriction:
This interface is not intended to be extended by clients.
```

I digged a little into the JUnit-Plugin and found the class

```
org.eclipse.jdt.internal.junit.model.JUnitModel.JUnitLaunchListener
```

that creates the ```ITestRunSession``` for the JUnit-Test-Launch. But this class unfortunately check's and handles JUnit-Tests only. :-(

To notify the listeners to ```ITestRunSession```, we will then have to call
```java
JUnitCorePlugin.getDefault().getNewTestRunListeners()
```
thats also internal API.

To get your ```JUnitStatus``` with TestNG run, I see three possibilities:

1. We use the internal API and develop an adapter, that registers itself as ```ILaunchListener``` and, by watching ```launchChanged(ILaunch)```, notifies Listeners to ```ITestRunSession``` about the TestNG-Test. No changes in your ```JUnitTestRunListener``` needed, but internal API is used. Side effects have to be checked!

2. Don't use internal API and you provide an extension point that works similiar to the Eclipse extension point ```org.eclipse.jdt.junit.testRunListeners``` but no internal API used.

3. We extends your plugin with a class
```TestNGTestRunListener extends JUnitTestRunListener implements ILaunchListener```
that has the same constructor as ```JUnitTestRunListener``` and works as adapter from ```ILaunchListener``` to your API.
This class must be instanced additional to ```JUnitTestRunListener``` in your plugin and the class will only handle
TestNG-Launches.

I would prefer 2. or 3., what would be your proposal?

**Comment by rherrmann** [comment]
Good point! It's been a long time since I last looked at this code. I thought that `ITestRunSession` et al are meant to represent a generic test run, but apparently, they belong to JUnit core.

Option 1 seems the shortest path to something useful. One side effect, most likely, will be that the JUnit view will also show progress for TestNG runs. Though only those TestNG users would notice who also use the JUnit view.
In addition, a click on the status bar will open the JUnit view, and its context menu shows an entry that is specific to the JUnit view.

If this works and has proven useful to TestNG users, we can work on resolving unwanted access to other plug-in's internals. Options 2 seems a sensible approach. An extension point that allows adapter plug-ins fro JUnit and TestNG to register something like a `testSessionProgressProvider`.

**Comment by makkimesser** [comment]
You are right, `ITestRunSession` belongs to Eclipse's JUnit-Integration and is not meant to be used by clients. So I think its not
a good way to use it and have all TestNG-Tests to be shown in JUnit and TestNG-View.

Just started some tests. First I see, that your JDT-Plugin does not export any package, so I can't access `JUnitTestRunListener` from my TestPlugin. Maybe this can be solved by creating a Fragment or with adding an export in `com.codeaffine.extras.jdt`.

Looping through `JUnitCorePlugin.getDefault().getNewTestRunListeners()` I can then access the instance of
`com.codeaffine.extras.jdt.internal.junitstatus.JUnitTestRunListener` and call the methods overriden from `org.eclipse.jdt.junit.TestRunListener` that will update your JUnitStatus-Bar.

I will test what can be done with this approach and we can decide whether to go further or not.

**Comment by makkimesser** [comment]
After doing some tests, I found that it's not as easy as I formerly thought to get it running without side effects. And, by having only limited time, I think it its not worth enough to follow further. So I closed this for now.
